import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { parse } from 'smol-toml';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { configureCodex } from '../dist/integrations/codex/install.js';
const root = mkdtempSync(join(tmpdir(), 'kurtel-codex-'));
mkdirSync(join(root, '.codex'));
const configPath = join(root, '.codex', 'config.toml'), rulesPath = join(root, 'AGENTS.md');
const originalConfig = '# Keep this comment\nmodel = "custom-model"\n[mcp_servers.other]\ncommand = "other-server"\n';
const originalRules = '# Project instructions\nKeep tests readable.\n';
writeFileSync(configPath, originalConfig); writeFileSync(rulesPath, originalRules);
configureCodex(root, { graphOnly: true });
const first = readFileSync(configPath, 'utf8'), rules = readFileSync(rulesPath, 'utf8');
configureCodex(root, { graphOnly: true }); assert.equal(readFileSync(configPath, 'utf8'), first); assert.equal(readFileSync(rulesPath, 'utf8'), rules);
const parsed = parse(first); assert.equal(parsed.model, 'custom-model'); assert.equal(parsed.mcp_servers.other.command, 'other-server');
assert(parsed.mcp_servers.kurtel.args.includes('--graph-only')); assert.deepEqual(parsed.mcp_servers.kurtel.env_vars, ["KURTEL_POLICY_FILE"]);
assert(first.startsWith(originalConfig)); assert(rules.startsWith(originalRules));
configureCodex(root, { allowRemember: true });
assert(parse(readFileSync(configPath, 'utf8')).mcp_servers.kurtel.args.includes('--allow-remember'));
configureCodex(root, { uninstall: true }); assert.equal(readFileSync(configPath, 'utf8'), originalConfig); assert.equal(readFileSync(rulesPath, 'utf8'), originalRules);
writeFileSync(configPath, '[mcp_servers.kurtel]\ncommand = "user-command"\n');
assert.throws(() => configureCodex(root), /unmanaged/); assert.match(readFileSync(configPath, 'utf8'), /user-command/);
writeFileSync(configPath, '# BEGIN KURTEL MCP\n'); assert.throws(() => configureCodex(root), /Malformed/);
assert.equal(readFileSync(rulesPath, 'utf8'), originalRules);
writeFileSync(configPath, originalConfig);
const cli = fileURLToPath(new URL('../dist/index.js', import.meta.url));
let result = spawnSync(process.execPath, [cli, 'install', 'codex', '--force', '--graph-only'], { cwd: root, encoding: 'utf8', windowsHide: true });
assert.equal(result.status, 0, result.stderr);
assert(parse(readFileSync(configPath, 'utf8')).mcp_servers.kurtel.args.includes('--graph-only'));
result = spawnSync(process.execPath, [cli, 'uninstall', 'codex'], { cwd: root, encoding: 'utf8', windowsHide: true });
assert.equal(result.status, 0, result.stderr); assert.equal(readFileSync(configPath, 'utf8'), originalConfig);
result = spawnSync(process.execPath, [cli, 'install', 'claude-code', '--force', '--graph-only'], { cwd: root, encoding: 'utf8', windowsHide: true });
assert.notEqual(result.status, 0); assert.match(result.stderr, /Codex MCP only/);
console.log('PASS: Codex project installation idempotence, settings/comments preservation, graph-only/write opt-ins, exact uninstall and conflict refusal.');
