// Memory mechanics in throwaway repositories: activation by project markers, not by kurtel.io access.
process.env.KURTEL_ACTIVATION ??= "markers";
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const fixture = mkdtempSync(join(tmpdir(), 'kurtel-codex-capture-'));
const root = join(fixture, 'repo'), home = join(fixture, 'home');
mkdirSync(root); mkdirSync(home);
process.env.HOME = home; process.env.USERPROFILE = home;
const { activateRepo, setMemoryEnabled } = await import('../dist/storage/state.js');
const { captureEnabled, setCaptureEnabled, readSession, sessionCaptureEnabled } = await import('../dist/integrations/session-capture.js');
const { captureCodex } = await import('../dist/integrations/codex/capture.js');
const { configureCodex } = await import('../dist/integrations/codex/install.js');
const { readKnowledge } = await import('../dist/storage/knowledge.js');
const cli = fileURLToPath(new URL('../dist/index.js', import.meta.url));
const input = { session_id: 'test', turn_id: 'turn-1', cwd: root, hook_event_name: 'UserPromptSubmit', prompt: 'Use the internal gateway.' };
captureCodex(root, input); assert.equal(readSession(root, 'codex:test').length, 0);
activateRepo(root);
mkdirSync(join(root, '.codex'));
const hooksPath = join(root, '.codex', 'hooks.json');
const other = { hooks: [{ type: 'command', command: 'echo custom' }] };
writeFileSync(hooksPath, JSON.stringify({ hooks: { Stop: [other] } }));
configureCodex(root, { capture: true });
assert(captureEnabled(root, 'codex')); assert(!captureEnabled(root));
assert(sessionCaptureEnabled(root, 'codex:test')); assert(!sessionCaptureEnabled(root, 'test'));
const installed = readFileSync(hooksPath, 'utf8');
configureCodex(root, { capture: true }); assert.equal(readFileSync(hooksPath, 'utf8'), installed);
assert.deepEqual(JSON.parse(installed).hooks.Stop[0], other);
assert.throws(() => configureCodex(root, { capture: true, graphOnly: true }), /Graph-only/);
captureCodex(root, input); captureCodex(root, input);
assert.equal(readSession(root, 'codex:test').length, 1);
captureCodex(root, { ...input, cwd: home, turn_id: 'wrong-root' });
assert.equal(readSession(root, 'codex:test').length, 1);
captureCodex(root, { ...input, hook_event_name: 'PreToolUse', tool_use_id: 'patch', tool_name: 'apply_patch', tool_input: { command: 'PRIVATE_SOURCE_PATCH' } });
captureCodex(root, { ...input, hook_event_name: 'PostToolUse', tool_use_id: 'read', tool_name: 'Read', tool_response: 'PRIVATE_SOURCE_FILE' });
const result = spawnSync(process.execPath, [cli, 'codex-capture', '--root', root], { cwd: root, env: process.env, input: JSON.stringify({ ...input, hook_event_name: 'Stop', last_assistant_message: 'I propose this convention.', transcript_path: 'never-open-this' }), encoding: 'utf8', windowsHide: true });
assert.equal(result.status, 0, result.stderr); assert.equal(result.stdout, '{}');
const store = readKnowledge(root);
assert.equal(store.events.length, 4); assert.equal(store.versions.length, 0);
assert(store.events.some(e => e.kind === 'proposal'));
assert(!store.events.some(e => e.kind === 'acceptance' || e.kind === 'outcome_verified'));
assert(store.sources.every(s => s.reference.startsWith('codex/session/')));
assert(!JSON.stringify(store).includes('PRIVATE_SOURCE'));
setMemoryEnabled(root, false);
captureCodex(root, { ...input, turn_id: 'disabled' }); assert.equal(readSession(root, 'codex:test').length, 4);
setMemoryEnabled(root, true);
setCaptureEnabled(root, true);
configureCodex(root, { graphOnly: true }); assert(!captureEnabled(root, 'codex')); assert(captureEnabled(root));
assert.deepEqual(JSON.parse(readFileSync(hooksPath, 'utf8')).hooks, { Stop: [other] });
configureCodex(root, { capture: true }); configureCodex(root, { uninstall: true });
assert(!captureEnabled(root, 'codex')); assert.equal(readSession(root, 'codex:test').length, 4);
assert.deepEqual(JSON.parse(readFileSync(hooksPath, 'utf8')).hooks, { Stop: [other] });
console.log('PASS: Codex capture opt-in, provider separation, provenance, deduplication, payload filtering, kill switch and hook installation/removal.');
