// Memory mechanics in throwaway repositories: activation by project markers, not by kurtel.io access.
process.env.KURTEL_ACTIVATION ??= "markers";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { fileURLToPath } from "node:url";
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const home = mkdtempSync(join(tmpdir(), 'kurtel-decision-'));
process.env.HOME = home; process.env.USERPROFILE = home;
const root = join(home, 'repo'); mkdirSync(root);
const { importDecisionSources, searchDecisionSources } = await import('../dist/memory/decision-sources.js');
const { recordDecisionTrace } = await import('../dist/memory/decision-trace.js');
const { readKnowledge } = await import('../dist/storage/knowledge.js');
const { explainKnowledge } = await import('../dist/memory/knowledge-history.js');
const record = { kind: 'pull_request', reference: 'https://github.com/example/repo/pull/1#discussion_r2', revision: 'r1', content: 'We keep events because retries need their original evidence. Recomputing lost history was rejected.', attribution: { provider: 'github', subject: '42', login: 'alice', kurtel_user_id: null, occurred_at: '2026-09-01T00:00:00Z', source_type: 'review_comments', status: null, identity_basis: 'github_api_account' } };
const page = { protocol: 1, repo: 'example/repo', records: [record] };
let store = importDecisionSources(root, page);
assert.equal(store.versions.length, 0, 'Ingestion never manufactures a decision');
assert.equal(importDecisionSources(root, page).revision, store.revision);
const source_id = store.sources[0].id;
assert.equal(searchDecisionSources(root, "original evidence").records[0].id, source_id);
assert.equal(searchDecisionSources(root, source_id).records[0].excerpt, record.content);
const input = { key: 'keep-events', source_id, decision_quote: 'We keep events', reason_quote: 'retries need their original evidence', alternatives: [{ source_id, quote: 'Recomputing lost history was rejected.' }], paths: ['src/events.ts'], event_ids: [store.events[0].id] };
const result = recordDecisionTrace(root, input); assert.equal(result.state, 'proposed');
store = readKnowledge(root);
recordDecisionTrace(root, input); assert.equal(readKnowledge(root).revision, store.revision);
assert.throws(() => recordDecisionTrace(root, { ...input, decision_quote: 'Something else' }), /key reused/);
assert.throws(() => recordDecisionTrace(root, { ...input, key: 'bad', reason_quote: 'Invented reason' }), /exact quotes/);
assert.throws(() => recordDecisionTrace(root, { ...input, key: 'bad', event_ids: ['nonexistent'] }), /Unknown observed event/);
const explanation = explainKnowledge(store, result.version_id);
assert.equal(explanation.status, 'explained');
assert.equal(explanation.causal_claim, 'caller_reported_not_independently_verified');
assert.equal(explanation.attribution[0].attribution.subject, '42');
assert.equal(explanation.reasons[0].to.record.content, input.reason_quote);
assert.equal(explanation.alternatives.length, 1);
const unknown = recordDecisionTrace(root, { key: 'unknown', source_id, decision_quote: input.decision_quote, paths: [] });
assert.equal(explainKnowledge(readKnowledge(root), unknown.version_id).status, 'missing_reason');
const chained = recordDecisionTrace(root, { key: 'chain', source_id, decision_quote: input.decision_quote, paths: [], motivated_by: [result.version_id] });
assert.equal(explainKnowledge(readKnowledge(root), chained.version_id).reasons.length, 2);
const edited = importDecisionSources(root, { ...page, records: [{ ...record, revision: 'r2', content: 'Updated review.' }] });
assert.equal(edited.sources.filter(s => s.kind === 'pull_request').length, 2);
assert.equal(explainKnowledge(edited, result.version_id).reasons[0].to.record.content, input.reason_quote);
const { activateRepo } = await import('../dist/storage/state.js'); activateRepo(root);
const client = new Client({ name: 'decision-trace-integration', version: '1' });
await client.connect(new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../dist/index.js', import.meta.url)), 'mcp', '--root', root, '--allow-remember'], env: { ...process.env }, stderr: 'pipe' }));
try {
  const call = async (name, args) => { const result = await client.callTool({ name, arguments: args }); assert(!result.isError); return JSON.parse(result.content.map(c => c.text ?? '').join('')); };
  const found = await call('search_decision_sources', { query: 'original evidence' });
  assert.equal(found.records[0].id, source_id);
  const saved = await call('record_decision', { ...input, key: 'mcp-real-trace' });
  assert.equal(saved.state, 'proposed');
  const why = await call('explain_decision', { query: saved.version_id });
  assert.equal(why.reasons[0].to.record.content, input.reason_quote);
  assert.equal(why.attribution[0].attribution.login, 'alice');
  assert.equal(why.sources[0].content, null, 'No full source payload in explanation');
} finally { await client.close(); }
console.log('PASS: immutable GitHub observations, attribution, grounded decision chains, alternatives, idempotence and explicit unknown reasons.');
